### ISSUE TITLE
error when attempting to build rust-bert

### ISSUE THREAD

**Issue by pablogranolabar** [guillaume-be/rust-bert#137]
from a pull of the repo today then cargo run --release:

```
Running `target/release/convert-tensor`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `3`: usage: target/release/convert-tensor source.npz destination.ot', src/convert-tensor.rs:19:5
stack backtrace:
   0:     0x55a56f15b0a0 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55a56f15b0a0 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a56f15b0a0 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55a56f15b0a0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55a56f17292c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x55a56f1592a2 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x55a56f15cd15 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55a56f15cd15 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55a56f15cd15 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x55a56f15c873 - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x55a56f15d4b1 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x55a56f15cff7 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
  12:     0x55a56f15b53c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55a56f15cf59 - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x55a56f171d01 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
  15:     0x55a56f1205b8 - convert_tensor::main::h1a355cc77e4a545c
  16:     0x55a56f1213ea - std::sys_common::backtrace::__rust_begin_short_backtrace::h9b741d2a6463928b
  17:     0x55a56f1284c5 - std::rt::lang_start::{{closure}}::he2609531be6e3aa1
  18:     0x55a56f15d8d7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h527fb2333ede305e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259:13
  19:     0x55a56f15d8d7 - std::panicking::try::do_call::h309d8aee8149866c
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
  20:     0x55a56f15d8d7 - std::panicking::try::h75a60c31fd16bfc6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
  21:     0x55a56f15d8d7 - std::panic::catch_unwind::h1f9892423e99bc00
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
  22:     0x55a56f15d8d7 - std::rt::lang_start_internal::hd5b67df56ca01dae
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51:25
  23:     0x55a56f120662 - main
  24:     0x7f2f26dea0b3 - __libc_start_main
  25:     0x55a56f11ee6e - _start
  26:                0x0 - <unknown>
```

**Comment by guillaume-be** [comment]
Hello @pablogranolabar ,

I believe the crate builds fine - the error message happens at runtime. When running without a specific target, the binary utility `convert-tensor` gets called. This binary is used to convert Pytorch weights to C-array used by libtorch.  The 4th line indicates that you need to provide a source and target file name for this tensor conversion. This is only useful if you want to convert an existing set of pytorch weights for use in this library.

I guess you would like to run an example from the library. In this case, can you please try for example:
`cargo run --example generation` (there are multiple other examples provided in the `/examples` folder)
and let me know if this works?

**Comment by pablogranolabar** [comment]
That seems to work:
```
$ cargo run --example generation
   Compiling autocfg v1.0.1
   Compiling libc v0.2.93
   Compiling cfg-if v1.0.0
   Compiling cc v1.0.67
   Compiling pkg-config v0.3.19
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.69
   Compiling memchr v2.3.4
   Compiling lazy_static v1.4.0
   Compiling serde_derive v1.0.125
   Compiling log v0.4.14
   Compiling itoa v0.4.7
   Compiling serde v1.0.125
   Compiling byteorder v1.4.3
   Compiling pin-project-lite v0.2.6
   Compiling bytes v1.0.1
   Compiling crc32fast v1.2.1
   Compiling openssl-probe v0.1.2
   Compiling bitflags v1.2.1
   Compiling ryu v1.0.5
   Compiling adler32 v1.2.0
   Compiling futures-core v0.3.14
   Compiling getrandom v0.2.2
   Compiling cfg-if v0.1.10
   Compiling ahash v0.4.7
   Compiling matches v0.1.8
   Compiling openssl v0.10.33
   Compiling typenum v1.13.0
   Compiling ppv-lite86 v0.2.10
   Compiling fnv v1.0.7
   Compiling foreign-types-shared v0.1.1
   Compiling version_check v0.9.3
   Compiling tinyvec_macros v0.1.0
   Compiling slab v0.4.2
   Compiling pin-utils v0.1.0
   Compiling rayon-core v1.9.0
   Compiling httparse v1.3.6
   Compiling scopeguard v1.1.0
   Compiling curl v0.4.35
   Compiling native-tls v0.2.7
   Compiling futures-task v0.3.14
   Compiling regex-syntax v0.6.23
   Compiling anyhow v1.0.40
   Compiling serde_json v1.0.64
   Compiling either v1.6.1
   Compiling futures-sink v0.3.14
   Compiling unicode-width v0.1.8
   Compiling futures-io v0.3.14
   Compiling once_cell v1.7.2
   Compiling getrandom v0.1.16
   Compiling semver-parser v0.7.0
   Compiling try-lock v0.2.3
   Compiling percent-encoding v2.1.0
   Compiling httpdate v0.3.2
   Compiling encoding_rs v0.8.28
   Compiling tower-service v0.3.1
   Compiling half v1.7.1
   Compiling rawpointer v0.2.1
   Compiling ndarray v0.13.1
   Compiling protobuf v2.22.1
   Compiling rust_tokenizers v6.2.2
   Compiling remove_dir_all v0.5.3
   Compiling number_prefix v0.3.0
   Compiling ipnet v2.3.0
   Compiling smallvec v1.6.1
   Compiling opaque-debug v0.3.0
   Compiling base64 v0.13.0
   Compiling cpuid-bool v0.1.2
   Compiling mime v0.3.16
   Compiling plotters-backend v0.3.0
   Compiling same-file v1.0.6
   Compiling glob v0.3.0
   Compiling oorandom v11.1.3
   Compiling cmake v0.1.45
   Compiling crossbeam-utils v0.8.3
   Compiling tokio v1.5.0
   Compiling num-traits v0.2.14
   Compiling memoffset v0.6.3
   Compiling indexmap v1.6.2
   Compiling num-complex v0.2.4
   Compiling num-integer v0.1.44
   Compiling rayon v1.5.0
   Compiling tracing-core v0.1.17
   Compiling regex-automata v0.1.9
   Compiling openssl-sys v0.9.61
   Compiling libz-sys v1.1.2
   Compiling bzip2-sys v0.1.10+1.0.8
   Compiling curl-sys v0.4.41+curl-7.75.0
   Compiling miniz_oxide v0.3.7
   Compiling futures-channel v0.3.14
   Compiling unicode-bidi v0.3.5
   Compiling hashbrown v0.9.1
   Compiling http v0.2.4
   Compiling foreign-types v0.3.2
   Compiling tinyvec v1.2.0
   Compiling generic-array v0.14.4
   Compiling itertools v0.10.0
   Compiling itertools v0.9.0
   Compiling textwrap v0.11.0
   Compiling semver v0.9.0
   Compiling form_urlencoded v1.0.1
   Compiling matrixmultiply v0.2.4
   Compiling unicode-normalization-alignments v0.1.12
   Compiling plotters-svg v0.3.0
   Compiling walkdir v2.3.2
   Compiling tracing v0.1.25
   Compiling unicode-normalization v0.1.17
   Compiling http-body v0.4.1
   Compiling rustc_version v0.2.3
   Compiling num_cpus v1.13.0
   Compiling time v0.1.43
   Compiling socket2 v0.3.19
   Compiling socket2 v0.4.0
   Compiling terminal_size v0.1.16
   Compiling filetime v0.2.14
   Compiling xattr v0.2.2
   Compiling dirs-sys v0.3.5
   Compiling fs2 v0.4.3
   Compiling atty v0.2.14
   Compiling aho-corasick v0.7.15
   Compiling futures-util v0.3.14
   Compiling csv-core v0.1.10
   Compiling mio v0.7.11
   Compiling want v0.3.0
   Compiling quote v1.0.9
   Compiling clap v2.33.3
   Compiling flate2 v1.0.14
   Compiling idna v0.2.2
   Compiling cast v0.2.5
   Compiling rand_core v0.6.2
   Compiling uuid v0.8.2
   Compiling rand_core v0.5.1
   Compiling tar v0.4.33
   Compiling dirs v3.0.1
   Compiling crossbeam-epoch v0.9.3
   Compiling crossbeam-channel v0.5.1
   Compiling ordered-float v2.1.1
   Compiling plotters v0.3.0
   Compiling regex v1.4.5
   Compiling bzip2 v0.3.3
   Compiling digest v0.9.0
   Compiling block-buffer v0.9.0
   Compiling url v2.2.1
   Compiling rand_chacha v0.3.0
   Compiling rand_chacha v0.2.2
   Compiling crossbeam-deque v0.8.0
   Compiling console v0.14.1
   Compiling tokio-util v0.6.6
   Compiling sha2 v0.9.3
   Compiling rand v0.8.3
   Compiling rand v0.7.3
   Compiling indicatif v0.15.0
   Compiling h2 v0.3.2
   Compiling tokio-native-tls v0.3.0
   Compiling criterion-plot v0.4.3
   Compiling tempfile v3.2.0
   Compiling thiserror-impl v1.0.24
   Compiling pin-project-internal v1.0.6
   Compiling thiserror v1.0.24
   Compiling pin-project v1.0.6
   Compiling zip v0.5.11
   Compiling hyper v0.14.5
   Compiling zip-extensions v0.6.0
   Compiling torch-sys v0.3.1
   Compiling hyper-tls v0.5.0
   Compiling bstr v0.2.15
   Compiling serde_urlencoded v0.7.0
   Compiling serde_cbor v0.11.1
   Compiling reqwest v0.11.3
   Compiling csv v1.1.6
   Compiling tinytemplate v1.2.1
   Compiling criterion v0.3.4
   Compiling cached-path v0.5.1
   Compiling tch v0.3.1
   Compiling rust-bert v0.14.0 (/home/gp/Documents/kompanion.ai/src/rust-bert)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 34s
     Running `target/debug/examples/generation`
Downloading https://huggingface.co/gpt2-medium/resolve/main/config.json [718B]... ✓ Done! Finished in 0 seconds
Downloading https://huggingface.co/gpt2-medium/resolve/main/vocab.json [1017.87KB]... ✓ Done! Finished in 0 seconds
Downloading https://huggingface.co/gpt2-medium/resolve/main/merges.txt [445.62KB]... ✓ Done! Finished in 0 seconds
Downloading https://huggingface.co/gpt2-medium/resolve/main/rust_model.ot [1.61GB].................... ✓ Done! Finished in 36 seconds
"The dog was taken to a local animal hospital where it was later euthanized.\n\nIf you have any information about this incident please contact"
"The dog was charged with animal cruelty, but was later released on $50,000 bond.\n\nAlertMe"
"The dog was injured in the attack, which was captured on video by a neighbor. The neighbor said the dog lunged at his neighbor\'s dog"
"The cat was returned to the owner.\n\nPolice said they were investigating the incident as a possible case of animal cruelty."
"The cat was released back into the wild on Wednesday.\n\nThe cat\'s owner, who cannot be named for legal reasons, said the animal appeared"
"The cat was in the cage, and it wasn\'t moving.\n\n\"What\'s wrong?\" I asked. \"Is it dead?\"\n\n"
```

**Comment by pablogranolabar** [comment]
Other examples are broken though:

```
$ cargo run openai_gpt
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/convert-tensor openai_gpt`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `3`: usage: target/debug/convert-tensor source.npz destination.ot', src/convert-tensor.rs:19:5
stack backtrace:
   0:     0x5591974ebd00 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5591974ebd00 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5591974ebd00 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5591974ebd00 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55919750358c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x5591974e9f02 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x5591974ed975 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5591974ed975 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5591974ed975 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x5591974ed4d3 - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x5591974ee111 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x5591974edc57 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
  12:     0x5591974ec19c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5591974edbb9 - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x559197502961 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
  15:     0x55919742fe73 - convert_tensor::main::h8401645f4ec249ea
                               at /home/gp/Documents/kompanion.ai/src/rust-bert/src/convert-tensor.rs:19:5
  16:     0x55919742e3d2 - core::ops::function::FnOnce::call_once::h75f5d65c097d9017
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
  17:     0x55919742435a - std::sys_common::backtrace::__rust_begin_short_backtrace::h4c76dbc56a200983
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:125:18
  18:     0x559197426ef6 - std::rt::lang_start::{{closure}}::h992910e2fe87a20f
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:66:18
  19:     0x5591974ee537 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h527fb2333ede305e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259:13
  20:     0x5591974ee537 - std::panicking::try::do_call::h309d8aee8149866c
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
  21:     0x5591974ee537 - std::panicking::try::h75a60c31fd16bfc6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
  22:     0x5591974ee537 - std::panic::catch_unwind::h1f9892423e99bc00
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
  23:     0x5591974ee537 - std::rt::lang_start_internal::hd5b67df56ca01dae
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51:25
  24:     0x559197426ec7 - std::rt::lang_start::h17a2b5b6020c2087
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:65:5
  25:     0x55919743022a - main
  26:     0x7f4d4844d0b3 - __libc_start_main
  27:     0x55919742365e - _start
  28:                0x0 - <unknown>
```
