### ISSUE TITLE
How to add suppor for the CodeBERT model? 

### ISSUE THREAD

**Issue by yijunyu** [guillaume-be/rust-bert#219]
I wonder how to support CodeBERT: https://huggingface.co/microsoft/codebert-base. It is popular in deep code learning and is based on RoBERTa. The python code base is here: https://github.com/microsoft/CodeBERT. If you don't have time, please give me some advices on how to achieve this, thank you !

**Comment by guillaume-be** [comment]
Hello @yijunyu ,

Thank you for your interest in the library and using CodeBERT. The RoBERTa architecture is already available in the library -- I have converted the weights and uploaded them at https://huggingface.co/microsoft/codebert-base. Can you please try loading them and let me know if this works for you? 

For reference weights stored on the model hub can be loaded and cached using the following:

```rust
use rust_bert::bert::BertConfig;
use rust_bert::resources::{RemoteResource, Resource};
use rust_bert::roberta::{RobertaConfigResources, RobertaForMaskedLM};
use rust_bert::Config;
use rust_tokenizers::tokenizer::RobertaTokenizer;
use tch::{nn, Device};

fn main() -> anyhow::Result<()> {
    //    Resources paths
    let config_resource = Resource::Remote(RemoteResource {
        url: "https://huggingface.co/microsoft/codebert-base/resolve/main/config.json".into(),
        cache_subdir: "codebert-base/config".into(),
    });
    let vocab_resource = Resource::Remote(RemoteResource {
        url: "https://huggingface.co/microsoft/codebert-base/resolve/main/vocab.json".into(),
        cache_subdir: "codebert-base/vocab".into(),
    });
    let merges_resource = Resource::Remote(RemoteResource {
        url: "https://huggingface.co/microsoft/codebert-base/resolve/main/merges.txt".into(),
        cache_subdir: "codebert-base/merges".into(),
    });
    let weights_resource = Resource::Remote(RemoteResource {
        url: "https://huggingface.co/microsoft/codebert-base/resolve/main/rust_model.ot".into(),
        cache_subdir: "codebert-base/model".into(),
    });

    let config_path = config_resource.get_local_path()?;
    let vocab_path = vocab_resource.get_local_path()?;
    let merges_path = merges_resource.get_local_path()?;
    let weights_path = weights_resource.get_local_path()?;

    let tokenizer = RobertaTokenizer::from_file(
        vocab_path.to_str().unwrap(),
        merges_path.to_str().unwrap(),
        false,
        false,
    )?;

    let mut vs = nn::VarStore::new(Device::cuda_if_available());
    let config = BertConfig::from_file(config_path);
    let model = RobertaForMaskedLM::new(&vs.root(), &config);
    vs.load(weights_path);

    Ok(())
}
```

**Comment by yijunyu** [comment]
Thanks a lot for the initial import. I was able to run the above script, which loads the original codebert model. However, I am not sure how to do fine-tuning with the rust_bert.ot, and our task requires a fine-tuning step before inferencing. At the moment, in python we could generate a fine-tuned model using pytorch, but the script `utils/convert_model.py` is unable to convert it into a `rust_model.ot`. I wonder whether there is any tweaks I could do? Our fine-tuned codebert model could be downloaded from here: http://bertrust.s3.amazonaws.com/codeBERT_pl.bin.

**Comment by yijunyu** [comment]
Thanks for the guidance. I will tackle the problem once the conversion can be done. Currently the stack trace is listed below:
```
$ python utils/convert_model.py codeBERT_pl.bin 
Traceback (most recent call last):
  File "/home/ubuntu/Documents/github.com/guillaume-be/rust-bert/utils/convert_model.py", line 21, in <module>
    for k, v in weights.items():
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RobertaClass' object has no attribute 'items'
```

When `print(weights)` is inserted to the convert_model.py at line 20, I got the following dump:

```
RobertaClass(
  (codeBert): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
    ...
  )
  (fc): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)
```

The last two lines may indicate that the model we saved has two more attributes:
```python
        self.codeBert = RobertaModel.from_pretrained("microsoft/codebert-base")
        self.fc = nn.Linear(768,768)
        self.classifier = nn.Linear(768,2)
```

However, the stack trace concerns a missing "item" attribute in `weights`, from the printed "weights" variable I don't see where to locate the attribute directly from the model.

**Comment by guillaume-be** [comment]
Hello @yijunyu ,
Could you please share the Python code that was used to serialize the model?

**Comment by yijunyu** [comment]
The main code is listed below:

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import RobertaConfig, RobertaModel

class RobertaClass(torch.nn.Module):
    def __init__(self):
        super(RobertaClass, self).__init__()
        self.codeBert = RobertaModel.from_pretrained("microsoft/codebert-base")
        self.fc = nn.Linear(768,768)
        self.classifier = nn.Linear(768,2)

    def forward(self, input_ids, attention_mask, token_type_ids):
        roberta_out = self.codeBert(input_ids = input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)
        hidden_state = roberta_out[0]
        pooler = hidden_state[:,0]
        pooler = F.relu(self.fc(pooler))
        pooler = F.dropout(pooler, 0.3)
        output = self.classifier(pooler)
        return output

model = RobertaClass()
model.to(device)
...
for epoch_i in range(0, opt.epochs):
      torch.save(model, 'codeBERT_pl.bin')
      model.train()
```

**Comment by guillaume-be** [comment]
Can you try saving the model state dict instead of the model itself, i.e. 
```python
torch.save(model.state_dict(), 'codeBERT_pl.bin')
```

**Comment by yijunyu** [comment]
The above conversion works! I can save the model into `rust_model.ot` and load it into the memory using the code fragment you shared:
```rust
let model = RobertaForMaskedLM::new(&vs.root(), &config);
```
Now I am at the next step, that is, to convert the custom architecture. I use the first alternative, RobertaSequenceClass, 
```rust
let model = RobertaSequenceClassification::new(&vs.root(), &config);
```
It can still load the model, but there seems to be missing the num_labels which should be 2 in our case.
```
thread 'main' panicked at 'num_labels not provided in configuration', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.17.0/src/roberta/roberta_model.rs:374:14
```
It is not found in the original configuration: https://huggingface.co/microsoft/codebert-base/resolve/main/config.json
I wonder whether I shall take the second way you suggested and feed it with this missing `num_labels` variable.

Here is the specific python code where we extend the RobertaClass:
```python
class RobertaClass(torch.nn.Module):
    def __init__(self):
        super(RobertaClass, self).__init__()
        self.codeBert = RobertaModel.from_pretrained("microsoft/codebert-base")
        self.fc = nn.Linear(768,768)
        self.classifier = nn.Linear(768,2)

    def forward(self, input_ids, attention_mask, token_type_ids):
        roberta_out = self.codeBert(input_ids = input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)
        hidden_state = roberta_out[0]
        pooler = hidden_state[:,0]
        pooler = F.relu(self.fc(pooler))
        pooler = F.dropout(pooler, 0.3)
        output = self.classifier(pooler)
        return output
```
How shall I add a new `forward_t` function into the adaptation ?

**Comment by guillaume-be** [comment]
Hello @yijunyu ,

I believe you can still use the first way and this should be an easy fix. For `SequenceClassification`, the models expect a mapping from label id to name, see for example in https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english/blob/main/config.json:
```json
"id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
}
```

Can you please update your configuration to provide the same mapping and try again?

**Comment by yijunyu** [comment]
Thanks @guillaume-be. I tried the following change by adapting what's in the url "https://huggingface.co/microsoft/codebert-base/resolve/main/config.json": 
```json
{
  "architectures": [
    "RobertaModel"
  ],
  "max_position_embeddings": 514,
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_past": true,
  "pad_token_id": 1,
  "type_vocab_size": 1,
  "vocab_size": 50265,
  "id2label": {
          "0": "positive",
          "1": "negative"
  },
  "label2id": {
          "positive": 0,
          "negative": 1
  }
}
```
Then I changed the `sequence_classification.rs` in the examples folder in the following lines:
```rust
    let config_resource = Resource::Remote(RemoteResource {
        url: "config.json".into(),
        // url: "https://huggingface.co/microsoft/codebert-base/resolve/main/config.json".into(),
        cache_subdir: "codebert-base/config".into(),
    });
    let merges_resource = Resource::Remote(RemoteResource {
        url: "https://huggingface.co/microsoft/codebert-base/resolve/main/merges.txt".into(),
        cache_subdir: "codebert-base/merges".into(),
    });
    let vocab_resource = Resource::Remote(RemoteResource {
        url: "https://huggingface.co/microsoft/codebert-base/resolve/main/vocab.json".into(),
        cache_subdir: "codebert-base/vocab".into(),
    });
    let weights_resource = Resource::Remote(RemoteResource {
        url: "https://bertrust.s3.amazonaws.com/rust_model.ot".into(),
        cache_subdir: "codebert-base/model".into(),
    });
    let config = SequenceClassificationConfig::new(ModelType::Roberta,
           weights_resource,
           config_resource,
           vocab_resource,
           Some(merges_resource),
           true, //lowercase
           None, //strip_accents
           None, //add_prefix_space
    );
```

When running
```bash
cargo run --example sequence_classification
```

I got the following error:
```
Error: Tch tensor error: cannot find the tensor named roberta.encoder.layer.1.attention.self.query.bias in /home/ubuntu/.cache/.rustbert/codebert-base/model/240f31f03e868b79c0fdb2ce224db8d431c081c7d04369e1f19a7efff173c6a1.9ad8d72bbe52b1a7dc528c38c0f4eb819bcc81ccd6fd289d6bb128d4183a3fe4
```
Note that every time rerun the example a different layer was reported in the error, for example:
```
Error: Tch tensor error: cannot find the tensor named roberta.encoder.layer.8.attention.self.key.bias in /home/ubuntu/.cache/.rustbert/codebert-base/model/240f31f03e868b79c0fdb2ce224db8d431c081c7d04369e1f19a7efff173c6a1.9ad8d72bbe52b1a7dc528c38c0f4eb819bcc81ccd6fd289d6bb128d4183a3fe4
```
I wonder whether I also need to change any thing else in the `config.json`. I noted that the original CodeBERT python code it has dropout 0.3 and activation relu functions, but they were not in the downloaded config.json (btw, adding them does not change the fact it will report this error by Tch).

**Comment by guillaume-be** [comment]
Closed via https://github.com/guillaume-be/rust-bert/pull/282, https://github.com/guillaume-be/rust-bert/pull/322
