### ISSUE TITLE
Convert-tensor throws error

### ISSUE THREAD

**Issue by raoulg** [guillaume-be/rust-bert#275]
1. setup up a Linux machine (ubuntu 20.04)
2. Installed rust, cloned rust-bert
3. run `cargo build` inside rust-belt
4. `cargo run zero_shot_classifictions.rs` from inside examples, but also `cargo run` from root dir

```
     Running `/home/azureuser/code/rust-bert/target/debug/convert-tensor zero_shot_classification.rs`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `3`: usage: /home/azureuser/code/rust-bert/target/debug/convert-tensor source.npz destination.ot', src/convert-tensor.rs:19:5
```

and

```
     Running "target/debug/convert-tensor"
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `3`: usage: target/debug/convert-tensor source.npz destination.ot', src/convert-tensor.rs:19:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
```

running with RUST_BACKTRACE=1:
```
     Running `/home/azureuser/code/rust-bert/target/debug/convert-tensor zero_shot_classification.rs`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `3`: usage: /home/azureuser/code/rust-bert/target/debug/convert-tensor source.npz destination.ot', src/convert-tensor.rs:19:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:181:5
   4: convert_tensor::main
             at /home/azureuser/code/rust-bert/src/convert-tensor.rs:19:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by raoulg** [comment]
Turns out, I had to run `cargo run --example  zero_shot_classification`!
