### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TorchError 

### ISSUE THREAD

**Issue by sbeckeriv** [guillaume-be/rust-bert#34]
Hello,

I was playing around with this library and I am able to produce a panic. I have a large file but the last line.. really where it says ", you can access detailed integration logs. " in the last line causes a panic. removing the that bit work appears to stop the panic. somewhere around this point. I hope this helps. 

My code is from the example folder:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=84b4c8f146e1229f2b2713677b5177da

Cargo.toml file
[dependencies]
rust-bert = "*"
failure = "*"

my test csv file
https://gist.github.com/sbeckeriv/0e2c387b9899e1916efd23654d660949

rustc 1.45.0-nightly (7ced01a73 2020-04-30)
A run with the backtrace set to full. 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TorchError { c_error: "stack expects a non-empty TensorList (stack at ../aten/src/ATen/native/TensorShape.cpp:969)\nframe #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7fc40279caaa in /home/becker/trash/bertku/target/debug/build/torch-sys-1cb99d9d0c4f3210/out/libtorch/libtorch/lib/libc10.so)\nframe #1: at::native::stack(c10::ArrayRef<at::Tensor>, long) + 0x1df (0x7fc4038bab6f in /home/becker/trash/bertku/target/debug/build/torch-sys-1cb99d9d0c4f3210/out/libtorch/libtorch/lib/libtorch_cpu.so)\nframe #2: <unknown function> + 0x1292d17 (0x7fc403c52d17 in /home/becker/trash/bertku/target/debug/build/torch-sys-1cb99d9d0c4f3210/out/libtorch/libtorch/lib/libtorch_cpu.so)\nframe #3: <unknown function> + 0x11af75d (0x7fc403b6f75d in /home/becker/trash/bertku/target/debug/build/torch-sys-1cb99d9d0c4f3210/out/libtorch/libtorch/lib/libtorch_cpu.so)\nframe #4: <unknown function> + 0x2e9adcf (0x7fc40585adcf in /home/becker/trash/bertku/target/debug/build/torch-sys-1cb99d9d0c4f3210/out/libtorch/libtorch/lib/libtorch_cpu.so)\nframe #5: <unknown function> + 0x11af75d (0x7fc403b6f75d in /home/becker/trash/bertku/target/debug/build/torch-sys-1cb99d9d0c4f3210/out/libtorch/libtorch/lib/libtorch_cpu.so)\nframe #6: <unknown function> + 0x5eb736 (0x55c0a3afa736 in target/debug/bertku)\nframe #7: <unknown function> + 0x5df985 (0x55c0a3aee985 in target/debug/bertku)\nframe #8: <unknown function> + 0x5d64f8 (0x55c0a3ae54f8 in target/debug/bertku)\nframe #9: <unknown function> + 0x5cce2c (0x55c0a3adbe2c in target/debug/bertku)\nframe #10: <unknown function> + 0x5bdb7f (0x55c0a3accb7f in target/debug/bertku)\nframe #11: <unknown function> + 0x5c4a55 (0x55c0a3ad3a55 in target/debug/bertku)\nframe #12: <unknown function> + 0x585d29 (0x55c0a3a94d29 in target/debug/bertku)\nframe #13: <unknown function> + 0x12adb5 (0x55c0a3639db5 in target/debug/bertku)\nframe #14: <unknown function> + 0x132f1e (0x55c0a3641f1e in target/debug/bertku)\nframe #15: <unknown function> + 0x12ba33 (0x55c0a363aa33 in target/debug/bertku)\nframe #16: <unknown function> + 0x1329e7 (0x55c0a36419e7 in target/debug/bertku)\nframe #17: <unknown function> + 0xdb7b9 (0x55c0a35ea7b9 in target/debug/bertku)\nframe #18: <unknown function> + 0xdaf0b (0x55c0a35e9f0b in target/debug/bertku)\nframe #19: <unknown function> + 0x6d6248 (0x55c0a3be5248 in target/debug/bertku)\nframe #20: <unknown function> + 0xdaee7 (0x55c0a35e9ee7 in target/debug/bertku)\nframe #21: <unknown function> + 0xdba4a (0x55c0a35eaa4a in target/debug/bertku)\nframe #22: __libc_start_main + 0xf3 (0x7fc40251d0b3 in /lib/x86_64-linux-gnu/libc.so.6)\nframe #23: <unknown function> + 0xd991e (0x55c0a35e891e in target/debug/bertku)\n" }

   0: failure::backtrace::internal::InternalBacktrace::new
             at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/backtrace/internal.rs:46
   1: failure::backtrace::Backtrace::new
             at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/backtrace/mod.rs:121
   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from
             at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/error/error_impl.rs:19
   3: <failure::error::Error as core::convert::From<F>>::from
             at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/error/mod.rs:36
   4: tch::wrappers::tensor_fallible_generated::<impl tch::wrappers::tensor::Tensor>::f_stack
             at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.1.7/src/wrappers/tensor_fallible_generated.rs:17322
   5: tch::wrappers::tensor_generated::<impl tch::wrappers::tensor::Tensor>::stack
             at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.1.7/src/wrappers/tensor_generated.rs:7217
   6: rust_bert::pipelines::question_answering::QuestionAnsweringModel::predict::{{closure}}
             at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.7.2/src/pipelines/question_answering.rs:318
   7: tch::wrappers::tensor::no_grad
             at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.1.7/src/wrappers/tensor.rs:452
   8: rust_bert::pipelines::question_answering::QuestionAnsweringModel::predict
             at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.7.2/src/pipelines/question_answering.rs:312
   9: bertku::main
             at src/main.rs:51
  10: std::rt::lang_start::{{closure}}
             at /home/becker/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  11: std::rt::lang_start_internal::{{closure}}
             at /rustc/7ced01a730e8fc1bae2f8d4369c26812c0484da4/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/7ced01a730e8fc1bae2f8d4369c26812c0484da4/src/libstd/panicking.rs:297
      std::panicking::try
             at /rustc/7ced01a730e8fc1bae2f8d4369c26812c0484da4/src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/7ced01a730e8fc1bae2f8d4369c26812c0484da4/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/7ced01a730e8fc1bae2f8d4369c26812c0484da4/src/libstd/rt.rs:51
  12: std::rt::lang_start
             at /home/becker/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  13: main
  14: __libc_start_main
  15: _start
', /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.1.7/src/wrappers/tensor_generated.rs:7217:9
stack backtrace:
   0:     0x55c0a3be1ea4 - backtrace::backtrace::libunwind::trace::he144fab28a4aed2d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55c0a3be1ea4 - backtrace::backtrace::trace_unsynchronized::h54d2de49d4561d5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55c0a3be1ea4 - std::sys_common::backtrace::_print_fmt::hc03d55f811cceef4
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55c0a3be1ea4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbc44d25334fa89cd
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55c0a3c07bbc - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x55c0a3bdbbd3 - std::io::Write::write_fmt::h4ee562ef1f300991
                               at src/libstd/io/mod.rs:1532
   6:     0x55c0a3be46d5 - std::sys_common::backtrace::_print::hc4186a5ac838159c
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55c0a3be46d5 - std::sys_common::backtrace::print::h61fb789361bb8109
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55c0a3be46d5 - std::panicking::default_hook::{{closure}}::hcd876594d255c932
                               at src/libstd/panicking.rs:198
   9:     0x55c0a3be4412 - std::panicking::default_hook::hfc205bc5ce834a89
                               at src/libstd/panicking.rs:218
  10:     0x55c0a3be4d32 - std::panicking::rust_panic_with_hook::h98fcd55ca23bf6e3
                               at src/libstd/panicking.rs:477
  11:     0x55c0a3be491b - rust_begin_unwind
                               at src/libstd/panicking.rs:385
  12:     0x55c0a3c065e1 - core::panicking::panic_fmt::hd101a87121fa411f
                               at src/libcore/panicking.rs:89
  13:     0x55c0a3c06403 - core::option::expect_none_failed::h4f0e89faa3179bf7
                               at src/libcore/option.rs:1272
  14:     0x55c0a3aa6e33 - core::result::Result<T,E>::unwrap::hfdcaa5d5ebd67e42
                               at /home/becker/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:1005
  15:     0x55c0a3639dca - tch::wrappers::tensor_generated::<impl tch::wrappers::tensor::Tensor>::stack::h5724a22a9145e765
                               at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.1.7/src/wrappers/tensor_generated.rs:7217
  16:     0x55c0a3641f1e - rust_bert::pipelines::question_answering::QuestionAnsweringModel::predict::{{closure}}::h2f305cc79a31d6b7
                               at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.7.2/src/pipelines/question_answering.rs:318
  17:     0x55c0a363aa33 - tch::wrappers::tensor::no_grad::h46fe95cf89870da2
                               at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.1.7/src/wrappers/tensor.rs:452
  18:     0x55c0a36419e7 - rust_bert::pipelines::question_answering::QuestionAnsweringModel::predict::hfa675df4580255af
                               at /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.7.2/src/pipelines/question_answering.rs:312
  19:     0x55c0a35ea7b9 - bertku::main::hcf5f95fd7aa784ef
                               at src/main.rs:51
  20:     0x55c0a35e9f0b - std::rt::lang_start::{{closure}}::h29b5c750fbd354e3
                               at /home/becker/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  21:     0x55c0a3be5248 - std::rt::lang_start_internal::{{closure}}::h86be2e33c1b2fc02
                               at src/libstd/rt.rs:52
  22:     0x55c0a3be5248 - std::panicking::try::do_call::h9468ed432eddf5f1
                               at src/libstd/panicking.rs:297
  23:     0x55c0a3be5248 - std::panicking::try::hda2b1d9056481eed
                               at src/libstd/panicking.rs:274
  24:     0x55c0a3be5248 - std::panic::catch_unwind::h8cbb401c5be5ca4d
                               at src/libstd/panic.rs:394
  25:     0x55c0a3be5248 - std::rt::lang_start_internal::h2403699d8e6ba133
                               at src/libstd/rt.rs:51
  26:     0x55c0a35e9ee7 - std::rt::lang_start::h91413199939c6997
                               at /home/becker/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  27:     0x55c0a35eaa4a - main
  28:     0x7fc40251d0b3 - __libc_start_main
  29:     0x55c0a35e891e - _start
  30:                0x0 - <unknown>
```

**Comment by guillaume-be** [comment]
@sbeckeriv Hello and thank you for trying out this crate!

I could reproduce the error using the example file you provided. However I do not believe the issue is caused by the QuestionAnswering model.

In the gist you shared:
```rust
    let string = fs::read_to_string("all.csv")
        .unwrap_or(String::from(""))
        .replace(|c: char| !c.is_ascii(), "")
        .replace(|c: char| c.is_whitespace(), " ")
        .replace(
            |c: char| c != '.' && !c.is_alphabetic() && !c.is_whitespace(),
            "",
        );
```
`string` will be of value `""` if ` fs::read_to_string` fails (` .unwrap_or(String::from(""))`). At line 24, col 181 in his file you have the character `—`. This is not a valid UTF-8 as expected by [read_to_string](https://doc.rust-lang.org/std/fs/fn.read_to_string.html). You can check it by checking the value of `string` before it enters the model.

This causes the context to be an empty string and the downstream pipeline to fail. Please read the file using a more robust method and pass the resulting string to the model - and let me know if it fixes it.

**Comment by sbeckeriv** [comment]
Hello @guillaume-be,

I understand a blank string would be a problem. line 22 i also have `dbg!(&string);` the string is not blank at this point.

I removed the `—` but it still fails for me. Im tying to figure out how to validate my string. I have this and z is Ok. I would expect it to error if it was invalid? 
```
    let z = String::from_utf8(string.as_bytes().into());
    dbg!(&z);
    let context_1 = z.unwrap(); 
```

I will look at removing more from my file. thanks.

**Comment by sbeckeriv** [comment]
Hello @guillaume-be,

I found `iconv -f utf8 -t ascii ` did give me an invalid error. This thread[1] suggested a tool that is html2text. I was able to run iconv without error.  I still get the same panic. If i remove the last word in the file it runs fine. Is there a limit on context? 

new panic csv file. 
https://gist.githubusercontent.com/sbeckeriv/2e976041967aacc48e5c0e27ff5eb672/raw/59c85c6d29c1930ff549317a85df822ae9155e9b/all.csv

I am hoping to dump a website's support page in as context and ask questions. Maybe this is not the right use case for QuestionAnsweringModel? 

Thanks again




[1] https://unix.stackexchange.com/questions/141539/iconv-illegal-input-sequence-why

**Comment by sbeckeriv** [comment]
thanks! it is no longer panics here.

**Comment by fitrailham** [comment]
i have same problem but diference case,` let date_time_ebr_loop: Option<String>  = Some(row.get("date_time_ebr").unwrap());
`

  for row in block.rows() {
        let date_time_ggsn_loop: Option<DateTime<Tz>>  = Some(row.get("date_time_ggsn").unwrap());
        let apn_ggsn_loop: Option<String> = Some(row.get("apn_ggsn").unwrap());
        let device_ggsn_loop: Option<String>  = Some(row.get("device_ggsn").unwrap());
        let date_time_ebr_loop: Option<String>  = Some(row.get("date_time_ebr").unwrap());
        let apn_ebr_loop: Option<String>  = Some(row.get("apn_ebr").unwrap());
        let device_name_ebr_loop: Option<String>  = Some(row.get("device_name_ebr").unwrap());
        let apn_pool_loop: Option<u64>  = Some(row.get("apn_pool").unwrap());
}

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromSql(OutOfRange)', examples\clickhouse1.rs:122:78
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:92
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\option.rs:1300
   3: core::result::Result<u32, clickhouse_rs::errors::Error>::unwrap<u32,clickhouse_rs::errors::Error>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:1037
   4: clickhouse1::main::main::{{closure}}
             at .\examples\clickhouse1.rs:122
   5: core::future::from_generator::{{impl}}::poll<generator-0>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:80
   6: clickhouse1::main::{{closure}}
             at .\examples\clickhouse1.rs:9
   7: core::future::from_generator::{{impl}}::poll<generator-0>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:80
   8: async_std::task::builder::{{impl}}::poll::{{closure}}<core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.9.0\src\task\builder.rs:199
   9: async_std::task::task_locals_wrapper::{{impl}}::set_current::{{closure}}<closure-0,core::task::poll::Poll<tuple<>>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.9.0\src\task\task_locals_wrapper.rs:60
  10: std::thread::local::LocalKey<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>>::try_with<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>,closure-0,core::task::poll::Poll<tuple<>>>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:272
  11: std::thread::local::LocalKey<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>>::with<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>,closure-0,core::task::poll::Poll<tuple<>>>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:248
  12: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current<closure-0,core::task::poll::Poll<tuple<>>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.9.0\src\task\task_locals_wrapper.rs:55
  13: async_std::task::builder::{{impl}}::poll<core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.9.0\src\task\builder.rs:197
  14: futures_lite::future::{{impl}}::poll<tuple<>,async_std::task::builder::SupportTaskLocals<core::future::from_generator::GenFuture<generator-0>>,core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.11.3\src\future.rs:526
  15: async_executor::{{impl}}::run::{{closure}}<tuple<>,async_std::task::builder::SupportTaskLocals<core::future::from_generator::GenFuture<generator-0>>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.0\src\lib.rs:236
  16: core::future::from_generator::{{impl}}::poll<generator-0>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:80
  17: async_executor::{{impl}}::run::{{closure}}<tuple<>,async_std::task::builder::SupportTaskLocals<core::future::from_generator::GenFuture<generator-0>>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.0\src\lib.rs:437
  18: core::future::from_generator::{{impl}}::poll<generator-0>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:80
  19: async_io::driver::block_on<tuple<>,core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-io-1.3.1\src\driver.rs:142
  20: async_global_executor::reactor::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>,tuple<>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-global-executor-2.0.2\src\reactor.rs:3
  21: async_global_executor::reactor::block_on<core::future::from_generator::GenFuture<generator-0>,tuple<>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-global-executor-2.0.2\src\reactor.rs:12
  22: async_global_executor::executor::block_on::{{closure}}<async_std::task::builder::SupportTaskLocals<core::future::from_generator::GenFuture<generator-0>>,tuple<>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-global-executor-2.0.2\src\executor.rs:26
  23: std::thread::local::LocalKey<async_executor::LocalExecutor>::try_with<async_executor::LocalExecutor,closure-0,tuple<>>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:272
  24: std::thread::local::LocalKey<async_executor::LocalExecutor>::with<async_executor::LocalExecutor,closure-0,tuple<>>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:248
  25: async_global_executor::executor::block_on<async_std::task::builder::SupportTaskLocals<core::future::from_generator::GenFuture<generator-0>>,tuple<>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-global-executor-2.0.2\src\executor.rs:26
  26: async_std::task::builder::{{impl}}::blocking::{{closure}}::{{closure}}<core::future::from_generator::GenFuture<generator-0>,tuple<>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.9.0\src\task\builder.rs:171
  27: async_std::task::task_locals_wrapper::{{impl}}::set_current::{{closure}}<closure-0,tuple<>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.9.0\src\task\task_locals_wrapper.rs:60
  28: std::thread::local::LocalKey<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>>::try_with<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>,closure-0,tuple<>>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:272
  29: std::thread::local::LocalKey<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>>::with<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>,closure-0,tuple<>>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:248
  30: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current<closure-0,tuple<>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.9.0\src\task\task_locals_wrapper.rs:55
  31: async_std::task::builder::{{impl}}::blocking::{{closure}}<core::future::from_generator::GenFuture<generator-0>,tuple<>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.9.0\src\task\builder.rs:168
  32: std::thread::local::LocalKey<core::cell::Cell<usize>>::try_with<core::cell::Cell<usize>,closure-0,tuple<>>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:272
  33: std::thread::local::LocalKey<core::cell::Cell<usize>>::with<core::cell::Cell<usize>,closure-0,tuple<>>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:248
  34: async_std::task::builder::Builder::blocking<core::future::from_generator::GenFuture<generator-0>,tuple<>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.9.0\src\task\builder.rs:161
  35: async_std::task::block_on::block_on<core::future::from_generator::GenFuture<generator-0>,tuple<>>
             at C:\Users\a_braincode\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.9.0\src\task\block_on.rs:33
  36: clickhouse1::main
             at .\examples\clickhouse1.rs:9
  37: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\Users\a_braincode\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\clickhouse1.exe` (exit code: 101)

Process finished with exit code 101

```

can you help me with this case
