### ISSUE TITLE
Keyword extraction model panics on some texts

### ISSUE THREAD

**Issue by laptou** [guillaume-be/rust-bert#363]
I've isolated the issue to the following example:

```rust
#[cfg(test)]
mod test {
    use rust_bert::pipelines::keywords_extraction::*;

    #[test]
    fn x() {
        let model = KeywordExtractionModel::new(KeywordExtractionConfig {
            ..Default::default()
        })
        .expect("failed to create keyword extraction model");

        let s = ["We had to try this"];
        let result = model.predict(&s).unwrap();

        println!("{result:?}");
    }
}
```

This consistently panics for me:
```
running 1 test
thread 'annotator::test::x' panicked at 'called `Result::unwrap()` on an `Err` value: Shape("expected one dim, got []")', /home/ibiyemi/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.20.0/src/pipelines/keywords_extraction/scorer.rs:82:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1090:23
   4: rust_bert::pipelines::keywords_extraction::scorer::cosine_similarity_score
             at /home/ibiyemi/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.20.0/src/pipelines/keywords_extraction/scorer.rs:80:5
   5: rust_bert::pipelines::keywords_extraction::scorer::<impl rust_bert::pipelines::keywords_extraction::pipeline::KeywordScorerType>::score_keywords
             at /home/ibiyemi/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.20.0/src/pipelines/keywords_extraction/scorer.rs:38:17
   6: rust_bert::pipelines::keywords_extraction::pipeline::KeywordExtractionModel::predict
             at /home/ibiyemi/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.20.0/src/pipelines/keywords_extraction/pipeline.rs:233:42
   7: swallow::annotator::test::x
             at ./src/annotator.rs:70:22
   8: swallow::annotator::test::x::{{closure}}
             at ./src/annotator.rs:63:12
   9: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test annotator::test::x ... FAILED

failures:

failures:
    annotator::test::x
```

I think in general there is a panic if the text results in zero or one keyword, because Torch squeezes the tensor into a scalar.

**Comment by guillaume-be** [comment]
Hello @laptou ,

Thank you very much for catching this and for the proposed fix!
